services:
  repocreate:
    build:
      context: ./build/
      dockerfile: Dockerfile  # Ensure this matches the actual file name
    image: 4ss078/repocreate:local
    environment:
      - CRON=0 22 * * *  # No quotes needed unless the value contains special characters
    restart: unless-stopped
    volumes:
      - /opt/autofs/mirror/apt-mirror/mirror:/repository  # Ensure space after the hyphen
      - /opt/repocreate/repocreate.json:/data/repocreate.json:ro
    networks:
      - repocreate_network
networks:
  repocreate_network:
    driver: bridge
